- name: "Server Info (Distribution/Version/ARQ)"
  debug:
    msg: "{{ ansible_distribution }}/{{ ansible_distribution_version }}/({{ ansible_architecture }})"

- name: "Check if host resolve fusion fqdn: {{ fusion_server_fqdn }}"
  shell: ping -c 1 -w 2 {{ fusion_server_fqdn }}
  register: fusion_ping_result
  ignore_errors: true

- name: "Add fusion host:{{ fusion_server_fqdn }} in /etc/hosts file"
  blockinfile:
    path: /etc/hosts
    block: |
      {{ fusion_server_ip }} {{ fusion_server_fqdn }}
    marker: "# {mark} Adding Fusion host"
  when: fusion_ping_result.rc == 2

#- Rhel Check TCP
- name: "Check TCP conectivity {{ fusion_server_fqdn }}:{{ fusion_port_rhel }}"
  wait_for:
    host: "{{ fusion_server_fqdn }}"
    port: "{{ fusion_port_rhel }}"
    state: started
    delay: 0
    timeout: 1
  register: fusion_tcp_connection
  when: ansible_distribution == 'RedHat'

#- Centos Check TCP
- name: "Check TCP conectivity {{ fusion_server_fqdn }}:{{ fusion_port_centos }}"
  wait_for:
    host: "{{ fusion_server_fqdn }}"
    port: "{{ fusion_port_centos }}"
    state: started
    delay: 0
    timeout: 1
  register: fusion_tcp_connection
  when: ansible_distribution == 'CentOS'

#- Suse Check TCP
- name: "Check TCP conectivity {{ fusion_server_fqdn }}:{{ fusion_port_suse }}"
  wait_for:
    host: "{{ fusion_server_fqdn }}"
    port: "{{ fusion_port_suse }}"
    state: started
    delay: 0
    timeout: 1
  register: fusion_tcp_connection
  when: ansible_distribution == 'SLES'

#- Ubuntu Check TCP
- name: "Check TCP conectivity {{ fusion_server_fqdn }}:{{ fusion_port_ubuntu }}"
  wait_for:
    host: "{{ fusion_server_fqdn }}"
    port: "{{ fusion_port_ubuntu }}"
    state: started
    delay: 0
    timeout: 1
  register: fusion_tcp_connection
  when: ansible_distribution == 'Ubuntu'

#- name: "Check UDP conectivity {{ fusion_server_fqdn }}:{{ fusion_port_rhel }}"
#  shell: nc -vu {{ fusion_server_fqdn }} {{ fusion_port_rhel }}
#  register: fusion_tcp_connection

#- Rhel Delet old config

- name: "Delete old configuration of fusion in main file (redhat)"
  ansible.builtin.file:
    path: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
    state: absent
  ignore_errors: true
  when: ansible_distribution == 'RedHat' and fusion_tcp_connection

#- Centos Delet old config

- name: "Delete old configuration of fusion in main file (Centos)"
  ansible.builtin.file:
    path: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
    state: absent
  ignore_errors: true
  when: ansible_distribution == 'CentOS' and fusion_tcp_connection

#- Suse Delet old config

- name: "Delete old configuration of fusion in main file (Suse)"
  ansible.builtin.file:
    path: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
    state: absent
  ignore_errors: true
  when: ansible_distribution == 'Suse' and fusion_tcp_connection

#- Ubuntu Delet old config

- name: "Delete old configuration of fusion in main file (Ubuntu)"
  ansible.builtin.file:
    path: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
    state: absent
  ignore_errors: true
  when: ansible_distribution == 'Ubuntu' and fusion_tcp_connection

#- Rhel Add Config

- name: "Add Fusion config in syslog (Redhat)"
  template:
    src: fusion_rsyslog_rhel.conf.j2
    dest: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
  notify:
  - reload daemon
  - restart rsyslog
  when: ansible_distribution == 'RedHat' and fusion_tcp_connection

  #- Centos Add Config

- name: "Add Fusion config in syslog (Centos)"
  template:
    src: fusion_rsyslog_centos.conf.j2
    dest: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
  notify:
  - reload daemon
  - restart rsyslog
  when: ansible_distribution == 'CentOS' and fusion_tcp_connection

 #- Ubuntu Add Config

- name: "Add fusion  config in syslog (Ubuntu)"
  template:
    src: fusion_rsyslog_ubuntu.conf.j2
    dest: "{{ rsyslogd_path }}{{ rsyslog_fusion_file }}"
  notify:
  - restart rsyslog
  when: ansible_distribution == 'Ubuntu' and fusion_tcp_connection

 #- Suse Add Config

- name: "Add Fusion config in syslog (SLES)"
  blockinfile:
    path: "{{ syslog_path }}{{ syslog_file }}"
    block: |
      filter f_auth { facility(auth, authpriv) ; };
      filter f_useremerg   { level(emerg)  and facility(user); };
      filter f_prg_audispd { program (audispd); };
      destination fusion { tcp("{{ fusion_server_fqdn }}" port({{ fusion_port_suse }})); };
      log { source(src); filter(f_useremerg); filter(f_prg_audispd);   destination(fusion); };
      log { source(src); filter(f_auth); destination(fusion); };
    marker: "# {mark} CyberSecurity v2.0"
  notify:
  - restart syslog
  when: (ansible_distribution == 'SLES') and fusion_tcp_connection

#- Rhel enabling port
- name: "Enabling port 51409 in selinux"
  seport:
    ports: 51409
    proto: tcp    
    setype: syslogd_port_t    
    state: present
  notify:
  - restart rsyslog
  ignore_errors: true
  when: (ansible_distribution == 'RedHat') and (ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8')

#- Centos enabling port
- name: "Enabling port 51411 in selinux"
  seport:
    ports: 51411
    proto: tcp    
    setype: syslogd_port_t    
    state: present
  notify:
  - restart rsyslog
  ignore_errors: true
  when: (ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8')

#- Suse enabling port
- name: "Enabling port 51413 in selinux"
  seport:
    ports: 51413
    proto: tcp    
    setype: syslogd_port_t    
    state: present
  notify:
  - restart syslog
  ignore_errors: true
  when: (ansible_distribution == 'SLES') 

#- Ubuntu enabling port
- name: "Enabling port 51412 in selinux"
  seport:
    ports: 51412
    proto: tcp    
    setype: syslogd_port_t    
    state: present
  notify:
  - restart rsyslog
  ignore_errors: true
  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version == '12' or ansible_distribution_major_version == '14' or ansible_distribution_major_version == '16' or  ansible_distribution_major_version == '18' or  ansible_distribution_major_version == '20' or  ansible_distribution_major_version == '22')

# Rhel y Centos Install Audit
- name: Install audit
  ansible.builtin.yum:
    name: audit
    state: latest
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8')

# Ubuntu Install Audit
- name: Install audit in ubuntu
  ansible.builtin.yum:
    name: auditd
    state: latest
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '12' or ansible_distribution_major_version == '14' or  ansible_distribution_major_version == '16' or  ansible_distribution_major_version == '18' or  ansible_distribution_major_version == '20' or  ansible_distribution_major_version == '22')

# Suse Install Audit
- name: Install audit in SLES
  ansible.builtin.yum:
    name: audit
    state: latest
  when: (ansible_distribution == 'SLES')

# Rhel 8 Install Auditd Plugins

- name: "Install audispd-plugins rhel8"
  ansible.builtin.yum:
    name: audispd-plugins
    state: latest
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == '8'

# Ubuntu Install Auditd Plugins

- name: Install audispd-plugins ubuntu
  ansible.builtin.yum:
    name: audispd-plugins
    state: latest
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '12' or ansible_distribution_major_version == '14' or ansible_distribution_major_version == '16' or  ansible_distribution_major_version == '18' or  ansible_distribution_major_version == '20' or  ansible_distribution_major_version == '22')

# Rhel/Centos Config Auditd.conf

- name: "Configure auditd.conf for rhel_7.1 ,2"
  template:
    src: auditd.conf_rhel_7.1_7.2.j2
    dest: "{{ auditd_path }}{{ auditd_file }}"
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and (ansible_distribution_version == '7.1' or ansible_distribution_version == '7.2')


- name: "Configure auditd.conf for rhel_7.3"
  template:
    src: auditd.conf_rhel_7.3.j2
    dest: "{{ auditd_path }}{{ auditd_file }}"
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version == '7.3'

- name: "Configure auditd.conf for rhel_7.4"
  template:
    src: auditd.conf_rhel_7.4.j2
    dest: "{{ auditd_path }}{{ auditd_file }}"
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version == '7.4'

- name: "Configure auditd.conf for rhel_7.5 ,6,7,8,9"
  template:
    src: auditd.conf_rhel_7.5_7_9.j2
    dest: "{{ auditd_path }}{{ auditd_file }}"
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and (ansible_distribution_version == '7.5' or ansible_distribution_version == '7.6' or ansible_distribution_version == '7.7' or ansible_distribution_version == '7.8' or ansible_distribution_version == '7.9')

- name: "Configure auditd.conf for rhel_8"
  template:
    src: auditd.conf_rhel_8.j2
    dest: "{{ auditd_path }}{{ auditd_file }}"
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == '8'

# Ubuntu Config Auditd.conf

- name: "Configure auditd.conf for ubuntu"
  template:
    src: auditd.conf_ubuntu_12_14.j2
    dest: "{{ auditd_path }}{{ auditd_file }}"
  notify:
  - Enable auditd
  - Stop auditd
  - Start auditd
  when:  ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '12' or ansible_distribution_major_version == '14' or ansible_distribution_major_version == '16' or  ansible_distribution_major_version == '18' or  ansible_distribution_major_version == '20' or  ansible_distribution_major_version == '22')

# Suse Config Auditd.conf

- name: "Configure auditd.conf in SLES"
  template:
    src: auditd.conf_suse.j2
    dest: /etc/audit/auditd.conf
  notify:
  - Enable auditd
  - Stop auditd
  - Start auditd
  when: (ansible_distribution == 'SLES')

# Rhel / Centos Audit.rules

- name: "Configure audit.rules"
  template:
    src: audit.rules.j2
    dest: "{{ auditd_rulesd_path }}{{ auditd_rulesd_file }}"
  notify:
  - Enable auditd
  - Stop auditd
  - Start auditd
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8')

# Ubuntu Audit.rules

- name: "Configure audit.rules ubuntu"
  template:
    src: audit.rules-ubuntu_12_14.j2
    dest: "{{ auditd_rulesd_path }}{{ auditd_rulesd_file }}"
  notify:
  - Enable auditd
  - Stop auditd
  - Start auditd
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '12' or ansible_distribution_major_version == '14' or  ansible_distribution_major_version == '16' or  ansible_distribution_major_version == '18' or  ansible_distribution_major_version == '20' or  ansible_distribution_major_version == '22') 

# Suse Audit.rules

- name: "Configure audit.rules in SLES"
  template:
    src: audit.rules-suse.j2
    dest: /etc/audit/audit.rules
  notify:
  - Enable auditd
  - Stop auditd
  - Start auditd
  when: (ansible_distribution == 'SLES')

# Rhel/Centos 7 Configure syslog.conf

- name:  "Configure syslog.conf"
  template:
    src: syslog.conf.j2
    dest: "{{ auditsp_path }}{{ auditsp_file }}"
  notify:
  - restart rsyslog
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == '7'

#Rhel/Centos 8 Configure syslog.conf

- name:  "Configure syslog.conf"
  template:
    src: syslog.conf_rhel_8.j2
    dest: "/etc/audit/plugins.d/{{ auditsp_file }}"
  notify:
  - reload daemon
  - restart rsyslog
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == '8'

# Ubuntu Configure syslog.conf

- name:  "Configure syslog.conf ubuntu"
  template:
    src: syslog.conf_ubuntu_12_14.j2
    dest: "{{ auditsp_path }}{{ auditsp_file }}"
  notify:
  - reload daemon
  - restart rsyslog
  when:  ansible_distribution == 'Ubuntu' and (ansible_distribution_major_version == '12' or ansible_distribution_major_version == '14' or  ansible_distribution_major_version == '16' or  ansible_distribution_major_version == '18' or  ansible_distribution_major_version == '20' or  ansible_distribution_major_version == '22')

# Sles Configure syslog.conf

- name:  "Configure syslog.conf in SLES"
  template:
    src: syslog.conf_suse.j2
    dest: "{{ auditsp_path }}{{ auditsp_file }}"
  notify:
  - restart syslog
  when: (ansible_distribution == 'SLES')

# Various Configurations

- name: find local6.none in /etc/rsyslog.conf
  shell: "grep -i 'local6.none' /etc/rsyslog.conf"
  register: check_local6
  ignore_errors: true
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8')

- name: add local6.none in /etc/rsyslog.conf
  replace:
    path: /etc/rsyslog.conf
    regexp: 'cron.none'
    replace: "cron.none;local6.none"
  ignore_errors: true
  notify:
  - reload daemon
  - restart rsyslog
  when: check_local6.stdout == "" and (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8')

- name: change the value of AUDITD_DISABLE_CONTEXTS from "yes" to "no"
  lineinfile:
    path:  /etc/sysconfig/auditd
    regexp: '^AUDITD_DISABLE_CONTEXTS='
    line: 'AUDITD_DISABLE_CONTEXTS="no"'
  notify:
  - Enable auditd
  - Stop auditd
  - Start auditd
  when: (ansible_distribution == 'SLES')

- name: change f_messages in {{ syslog_path }}{{ syslog_file }}
  replace:
    path:   "{{ syslog_path }}{{ syslog_file }}"
    regexp: '^filter f_messages.*$'
    replace: "filter f_messages   { not facility(news, mail) and not filter(f_iptables) and not filter(f_prg_audispd); };"
  ignore_errors: true
  notify:
  - restart syslog
  when: (ansible_distribution == 'SLES')
  notify:
  - restart syslog
  when: (ansible_distribution == 'SLES')
